### ISSUE TITLE
Mobile Visibility Issue with Readmap Images and Social Media Links

### ISSUE THREAD

**Issue by shnartho** [shnartho/metasurfai-frontend#1]
In version 1.0 of the project, the Readmap section images are compressed into one place in mobile devices , affecting the readability and visual appeal of the section. Social media links are not functional. This issue aims to address these two issues by properly organizing the images within the Readmap section and ensuring that social media links are correctly configured and operational.

Also, consider adding links to our Discord and Twitter accounts for better community engagement.

Let's prioritize fixing these issues to enhance user experience and community interaction.

**Comment by JemalSmb** [comment]
Issue resolved, pending pushing to repo.

~ J.S.

**Comment by shnartho** [comment]
perfect!
